name = "rust-with-typescript"
main = "dist/_worker.js/index.js"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"

[vars]
RUST_RUNNER_URL = "https://rust-sandbox-runner.fly.dev/run"

